/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cy_pdl.h"
#include "cyhal.h"
#include "cybsp.h"
#include "cy_retarget_io.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define UART_IRQ_PRIORITY       (3)
#define COMPARE_VALUE_DELTA     (1000)
#define DELAY_BETWEEN_READ_MS   (100)

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
uint32_t        g_period;               /* Variable to store period value of TCPWM block */
int32_t         g_compare0Value;        /* Variable to store the CC0 value of TCPWM block */
int32_t         g_compare1Value;        /* Variable to store the CC1 value of TCPWM block */
volatile bool   g_uartReadFlag = false; /* Variable to indicate receive data is available or not */

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: handle_UART_Event
 * Summary:
 *  UART event handler callback function. Sets the read flag to true upon successful reception of data.
 * Parameters:
 *  handlerArg - argument for the handler provided during callback registration
 *  event - interrupt cause flags
 * Return:
 *  none
 **********************************************************************************************************************
 */
 void handle_UART_Event(void *handlerArg, cyhal_uart_event_t event)
{
    (void)handlerArg;

    if (CYHAL_UART_IRQ_RX_DONE == (event & CYHAL_UART_IRQ_RX_DONE))
    {
        /* Set read flag */
        g_uartReadFlag = true;
    }
    else
    {
        CY_ASSERT(0);
    }
}

/**********************************************************************************************************************
 * Function Name: print_Instructions
 * Summary:
 *  Prints set of instructions.
 * Parameters:
 *  none
 * Return:
 *  none
 **********************************************************************************************************************
 */
void print_Instructions(void)
{
    printf("====================================================\r\n"
           "Instructions:\r\n"
           "====================================================\r\n"
           "Press 's' : To increase the duty cycle\r\n"
           "Press 'w' : To decrease the duty cycle\r\n"
           "Press 'a' : To shift waveform towards left\r\n"
           "Press 'd' : To shift waveform towards right\r\n"
           "====================================================\r\n");
}

/**********************************************************************************************************************
 * Function Name: process_Key_Press
 * Summary:
 *  Function to process the key pressed. Depending on the command passed as parameter, new compare values are calculated.
 *  The values are written to the respective buffer registers and a compare swap is issued.
 * Parameters:
 *  keyPressed - command read through terminal
 * Return:
 *  none
 **********************************************************************************************************************
 */
void process_Key_Press(char keyPressed)
{
    printf("Pressed key: %c\r\n", keyPressed);

    switch(keyPressed)
    {
        /* Increase duty cycle */
        case 's':
            g_compare0Value += COMPARE_VALUE_DELTA;
            g_compare1Value += COMPARE_VALUE_DELTA;
            if( g_compare0Value > g_period )
                g_compare0Value = g_period;
            if( g_compare1Value > g_period )
                g_compare1Value = g_period;
            break;
        /* Decrease duty cycle */
        case 'w':
            g_compare0Value -= COMPARE_VALUE_DELTA;
            g_compare1Value -= COMPARE_VALUE_DELTA;
            if( g_compare0Value < 0 )
                g_compare0Value = 0;
            if( g_compare1Value < 0 )
                g_compare1Value = 0;
            break;
        /* Shift waveform to left */
        case 'a':
            g_compare0Value -= COMPARE_VALUE_DELTA;
            g_compare1Value += COMPARE_VALUE_DELTA;
            if( g_compare0Value < 0 )
                g_compare0Value = 0;
            if( g_compare1Value > g_period )
                g_compare1Value = g_period;
            break;
        /* Shift waveform to right */
        case 'd':
            g_compare0Value += COMPARE_VALUE_DELTA;
            g_compare1Value -= COMPARE_VALUE_DELTA;
            if( g_compare0Value > g_period )
                g_compare0Value = g_period;
            if( g_compare1Value < 0 )
                g_compare1Value = 0;
            break;
        default:
            printf("Wrong key pressed !! See below instructions:\r\n");
            print_Instructions();
            return;
    }

    printf("Period: %lu\tCompare0: %ld\tCompare1: %ld\r\n",
          (unsigned long)g_period, (long)g_compare0Value,
          (long)g_compare1Value);

    /* Set new values for CC0/1 compare buffers */
    Cy_TCPWM_PWM_SetCompare0BufVal(PWM_VARIABLE_HW,
                                   PWM_VARIABLE_NUM,
                                   g_compare0Value);
    Cy_TCPWM_PWM_SetCompare1BufVal(PWM_VARIABLE_HW,
                                   PWM_VARIABLE_NUM,
                                   g_compare1Value);

    /* Trigger compare swap with its buffer values */
    Cy_TCPWM_TriggerCaptureOrSwap_Single(PWM_VARIABLE_HW,
                                         PWM_VARIABLE_NUM);
}

/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function.
 * Parameters:
 *  none
 * Return:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
    cy_rslt_t result;
    char uart_read_value; /* Variable to store the read command through UART */

    /* Initialize the device and board peripherals */
    result = cybsp_init() ;
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Enable global interrupts */
    __enable_irq();

    /* Initialize retarget-io to use the debug UART port */
    cy_retarget_io_init(CYBSP_DEBUG_UART_TX, CYBSP_DEBUG_UART_RX,
                        CY_RETARGET_IO_BAUDRATE);

    /* The UART callback handler registration */
    cyhal_uart_register_callback(&cy_retarget_io_uart_obj, handle_UART_Event,
                                 NULL);

    /* Enable UART events to get notified on receiving
     * RX data and on RX errors */
    cyhal_uart_enable_event(&cy_retarget_io_uart_obj,
                            (cyhal_uart_event_t)(CYHAL_UART_IRQ_RX_ERROR |
                            CYHAL_UART_IRQ_RX_DONE),
                            UART_IRQ_PRIORITY, true);

    /* Change the TCPWM configuration to use group trigger #0 as its starting trigger.
     * To use a group trigger, 'startInput' requires value calculated with this formula:
     * 2 (for fixed value 0/1) + TCPWM1_TR_ONE_CNT_NR + groupTriggerNo
     */
    PWM_VARIABLE_config.startInputMode = CY_TCPWM_INPUT_RISINGEDGE;
    PWM_VARIABLE_config.startInput = 2 + TCPWM1_TR_ONE_CNT_NR;
    PWM_FIXED_config.startInputMode = CY_TCPWM_INPUT_RISINGEDGE;
    PWM_FIXED_config.startInput = 2 + TCPWM1_TR_ONE_CNT_NR;

    /* Initialize the TCPWM block */
    Cy_TCPWM_PWM_Init(PWM_VARIABLE_HW, PWM_VARIABLE_NUM,
                      &PWM_VARIABLE_config);
    Cy_TCPWM_PWM_Init(PWM_FIXED_HW, PWM_FIXED_NUM,
                      &PWM_FIXED_config);

    /* Enable the TCPWM block */
    Cy_TCPWM_PWM_Enable(PWM_VARIABLE_HW, PWM_VARIABLE_NUM);
    Cy_TCPWM_PWM_Enable(PWM_FIXED_HW, PWM_FIXED_NUM);

    /* Fetch the initial values of period, CC0 and CC1 registers configured
     * through the design file
     */
    g_period = Cy_TCPWM_PWM_GetPeriod0(PWM_VARIABLE_HW, PWM_VARIABLE_NUM);
    g_compare1Value = Cy_TCPWM_PWM_GetCompare1Val(PWM_VARIABLE_HW,
                                                 PWM_VARIABLE_NUM);
    g_compare0Value = Cy_TCPWM_PWM_GetCompare0Val(PWM_VARIABLE_HW,
                                                 PWM_VARIABLE_NUM);

    /* Start the TCPWM block simultaneously */
    Cy_TrigMux_SwTrigger(TRIG_OUT_MUX_5_TCPWM1_ALL_CNT_TR_IN0, CY_TRIGGER_TWO_CYCLES);

    /* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
    printf("\x1b[2J\x1b[;H");

    printf("***********************************************************\r\n"
           "PDL: TCPWM in PWM Mode with Dual Compare/Capture\r\n"
           "***********************************************************\r\n\n");

    print_Instructions();

    for (;;)
    {
        /* Begin asynchronous RX read */
        cyhal_uart_read_async(&cy_retarget_io_uart_obj,
                              (void*) &uart_read_value,
                              sizeof(uart_read_value));

        /* Check if the read flag has been set by the callback */
        if(g_uartReadFlag)
        {
            /* Clear read flag */
            g_uartReadFlag = false;

            /* Process the command and modify the compare values to change the
             * duty cycle and phase.
             */
            process_Key_Press(uart_read_value);
        }

        /* Delay between next read */
        cyhal_system_delay_ms(DELAY_BETWEEN_READ_MS);
    }
}

/* [] END OF FILE */
